### PR TITLE
Be more strict with id capture group when creating header links

### PR DESCRIPTION
**Pull request by paulbrimicombe**
🧐 What?

- An HTML element within a heading that has an `id` (e.g. an image) can get repeated in the HTML output
- This is because the `id` capture group isn't strict enough

🛠 How

- Make the `id` capture group more strict so that it stops at the first `"` character

👀 See 

Try adding an image to a header and see that it comes out twice:

image

🐞 Related issue

I haven't raised one, but happy to....

### CODE REVIEW

**Comment by stephegn** [comment]
Good catch! I wonder if it's worth adding a quick test for this 🤔

**Comment by kevin-castillo-bbc** [comment]
It looks like jest needs an upgrade :D

**Comment by stephegn** [comment]
> > Good catch! I wonder if it's worth adding a quick test for this 🤔
> 
> I've just added a test. It seems that it screws things up for any HTML content that has `">` in it.

Now Jest has been upgraded the tests are passing. It looks like the test covers that case, am I missing something?

**Comment by paulbrimicombe** [comment]
> It looks like the test covers that case, am I missing something?

Yes, the new test I added covers the case where the regex matches too much text @stephegn

**Comment by stephegn** [comment]
> > It looks like the test covers that case, am I missing something?
> 
> Yes, the new test I added covers the case where the regex matches too much text @stephegn

Ahh I see. The bug was worse than we thought! I'll approve this and get it tagged :)

**Review by stephegn — APPROVED** [review]

**Pull request merged**
